config/routes.rb
Rails.application.routes.draw do
  post 'messages', to: "messages#create"
  mount Ckeditor::Engine => '/ckeditor'
  resources :notifications
  resources :vacations
  resources :salaries do
    get '/try_salary', to: 'salaries#try_salary', as: 'try_salary', on: :collection
  end
  resources :contracts
  get 'welcome/index'
  get 'welcome/indexlog'
  resources :application do
    get 'application/current_language', to: 'application#current_language', as: 'c_language', on: :collection
  end
  resources :languages do
      get '/change_language', to: 'languages#change_language', as: 'change_language', on: :collection

      get '/current_language', to: 'languages#current_language', as: 'c_language', on: :collection
  end


  resources :events
  resources :devices do
    get '/devices.xls', to: 'devices#report_devices', as: 'export', on: :collection
    collection {post :import}
    resources :maintainces do
      get '/device_maintainces.xls', to: 'maintainces#export_maintainces', as: 'export', on: :collection
    end
  end

  resources :users,:only => [:edit,:update]
  get 'users/index', to: 'users#index'
  get 'users/disabled_users_index', to: 'users#disabled_users_index', as: 'disabled_users_index'
  get 'users/:id/edit', to: 'users#edit'
  put 'users/:id/update', to: 'users#update'
  get 'users/:id/reset_password', to: 'users#reset_password', as: 'users_reset_password'
  get 'users/:id/disable_user', to: 'users#disable_user', as: 'user_disable'
  get 'users/:id/enable_user', to: 'users#enable_user', as: 'user_enable'


	devise_for :users, controllers: {
  	registrations: 'users/registrations',
  	sessions: 'users/sessions',
  	passwords: 'users/passwords',
  }

  authenticated :user do
  	root "welcome#indexlog", as: "authenticated_root"
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/maintaince.rb
class Maintaince < ApplicationRecord
  belongs_to :user
  belongs_to :device
end

app/controllers/maintainces_controller.rb
class MaintaincesController < ApplicationController
  before_action :set_maintaince, only: [:show, :edit, :update, :destroy]
  before_action :set_device
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /maintainces
  # GET /maintainces.json
  def index
    respond_to do |format|
    format.html
    format.json { render json: MaintainceDatatable.new(params,{view_context: view_context,device: @device, current_user: current_user}) }
    end
  end

  # GET /maintainces/1
  # GET /maintainces/1.json
  def show
  end

  # GET /maintainces/new
  def new
    @maintaince = @device.maintainces.build

  end

  # GET /maintainces/1/edit
  def edit
  end

  # POST /maintainces
  # POST /maintainces.json
  def create
    @maintaince = current_user.maintainces.new(maintaince_params)
    @maintaince.device = @device
    respond_to do |format|
      if @maintaince.save
        format.html { redirect_to @maintaince.device, success: t('app_common.models.maintainces.actions.created') }
        format.json { render :show, status: :created, location: @maintaince }
      else
        format.html { render :new }
        format.json { render json: @maintaince.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /maintainces/1
  # PATCH/PUT /maintainces/1.json
  def update
    respond_to do |format|
      if @maintaince.update(maintaince_params)
        format.html { redirect_to device_maintaince_path(@maintaince.device.id,@maintaince), info: t('app_common.models.maintainces.actions.created') }
        format.json { render :show, status: :ok, location: @maintaince }
      else
        format.html { render :edit }
        format.json { render json: @maintaince.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /maintainces/1
  # DELETE /maintainces/1.json
  def destroy
    @maintaince.destroy
    respond_to do |format|
      format.html { redirect_to device_maintainces_url(@device), danger: 'Maintaince was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def export_maintainces()
    @maintainces = User.joins(:devices, :maintainces).select('users.full_name as done_by,devices.name as device ,
      maintainces.name, maintainces.description, maintainces.date').where(devices:{user_id: @device.user_id})
     render xlsx: 'Reporte mantenimientos '+ Time.now.to_s,
        template: 'reports/export_maintainces.xlsx.axlsx'
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:device_id])
    end
    def set_maintaince
      @maintaince = Maintaince.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def maintaince_params
      params.require(:maintaince).permit(:name, :description, :date)
    end
end

app/helpers/maintainces_helper.rb
module MaintaincesHelper
end

app/views/maintainces/_form.html.erb
<div class="card-body">
  <%= form_with(model:  [@device,@maintaince], local: true) do |f| %>
    <% if @maintaince.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@maintaince.errors.count, "error") %> prohibited this maintaince from being saved:</h2>

        <ul>
        <% @maintaince.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <form class="form-horizontal">
    <div class="form-group row">
      <%= f.label :name,t('activerecord.attributes.maintaince.name'), class:"col-sm-3 col-form-label" %>
      <div class="col-sm-8">
        <%= f.text_field :name, autofocus: true, autocomplete: "text" , class:"form-control"%>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :description,t('activerecord.attributes.maintaince.description'), class: "col-sm-3 col-form-label" %>
      <div class="col-sm-8">
        <%= f.text_area :description, class: "form-control"%> 
      </div>
    </div>
    <div class="form-group row">
      <%=f.label :date,t('activerecord.attributes.maintaince.date'), class:"col-sm-3 col-form-label"%>
      <div class="col-sm-8">
        <%= f.date_field :date, required: true, autofocus: true, class:"forms_field-input"%>
      </div>
    </div>
    <div class="form-group row">
      <div class="offset-sm-2 col-sm-8">
        <%= f.submit  class:"btn btn-primary" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="offset-sm-2 col-sm-8">
        <%= link_to t('helpers.button.back'), :back , class:"btn btn-primary fa fa-arrow-left"%>
      </div>
    </div>
  </form>
  <% end %>
</div><!-- /.card-body -->

app/views/maintainces/edit.html.erb
<%=render 'layouts/partials/navbar'%>
<div class="center-style-app">
  <div class="content-wrapper">
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <h2><%=t('activerecord.models.maintaince.other')%></h2>
          <div class="card card-primary">
            <div class="card-header">
              <h3><%=t('app_common.edits.editing', model: model_name_singular(Maintaince))%> <%=@maintaince.name%></h3>
              <div class="card-tools">
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                  <i class="fa fa-minus"></i></button>
              </div>
            </div>
            <%= render 'form', maintaince: @maintaince %>
          </div>
          <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
  <%=render 'layouts/partials/footer'%>
  </div>
</div>

app/views/maintainces/index.html.erb
<%= render 'layouts/partials/navbar'%>
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="col-md-8">
        <p id="notice"><%= notice %></p>

        <h1><%=t('activerecord.models.maintaince.other')%></h1>
        <div style="margin-bottom: 20px;margin-top: 20px; ">
          <%if can? :create, Maintaince%>
            <%= link_to t('helpers.button.add', model: model_name_singular(Maintaince)), new_device_maintaince_path, class:'btn btn-primary '%>
          <%end%>
              <%= link_to 'Exportar Excel',export_device_maintainces_path(), class:'btn btn-primary '%>
        </div>
        <table id="maintainces-datatable" data-source="<%= device_maintainces_path(format: :json) %>">
          <thead >
            <tr>
              <th><%=Maintaince.human_attribute_name(:done_by)%> </th>
              <th><%=Maintaince.human_attribute_name(:name)%></th>
              <th><%=Maintaince.human_attribute_name(:description)%> </th>
              <th><%=Maintaince.human_attribute_name(:date)%></th>
              <th><%=Maintaince.human_attribute_name(:device)%></th>
              <th><%=t('app_common.tables.options')%></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
  </section>
  <%=render 'layouts/partials/footer'%>
</div>
<script>
  document.addEventListener('turbolinks:load', function() {
    maintaincesdt.ajax_datatable('#maintainces-datatable');
  });
</script>

app/views/maintainces/new.html.erb
<%=render 'layouts/partials/navbar'%>

<div class="center-style-app">
  <div class="content-wrapper">
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <h2>Mantenimientos</h2>
          <div class="card card-primary">
            <div class="card-header">
              <h3>Nuevo mantenimiento</h3>
              <div class="card-tools">
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                  <i class="fa fa-minus"></i></button>
              </div>
            </div>
            <%= render 'form', device: @maintaince %>
          </div>
          <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
  <%=render 'layouts/partials/footer'%>
  </div>
</div>

app/views/maintainces/show.html.erb
<%=render 'layouts/partials/navbar'%>
<div class="center-style-app">
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <h2><%=t('activerecord.models.maintaince.other')%></h2>
            <p id="notice"><%= notice %></p>
            <div class="card card-primary">
              <div class="card-header">
                  <h3><%=t('app_common.shows.showing', model: model_name_singular(Maintaince))%> <%=@maintaince.device.name%></h3>
                <div class="card-tools">
                  <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                          title="Collapse">
                    <i class="fa fa-minus"></i></button>
                </div>
              </div>
              <div class="card-body">
                <form class="form-horizontal">
                   <div class="form-group row">
                    <div class= "col-sm-4 col-form-label">
                      <%= "<strong>Usuario del dispositivo</strong>".html_safe%>
                    </div>
                    <div class=" col-sm-7">
                      <div class="form-control">
                        <%= @maintaince.user.full_name%>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class= "col-sm-4 col-form-label">
                      <%= "<strong>Dispositivo</strong>".html_safe%>
                    </div>
                    <div class=" col-sm-7">
                      <div class="form-control">
                        <%= @maintaince.device.name%>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class= "col-sm-4 col-form-label">
                      <%= "<strong>Número del dispositivo</strong>".html_safe%>
                    </div>
                    <div class=" col-sm-7">
                      <div class="form-control">
                        <%= @maintaince.device.number %>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class= "col-sm-4 col-form-label">
                      <%= "<strong>Mantenimiento</strong>".html_safe%>
                    </div>
                    <div class=" col-sm-7">
                      <div class="form-control">
                        <%= @maintaince.name %>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class= "col-sm-4 col-form-label">
                      <%= "<strong>Description</strong>".html_safe%>
                    </div>
                    <div class=" col-sm-7">
                      <div >
                        <textarea class="form-control" rows="2" placeholder="<%= @maintaince.description %> " disabled></textarea>
                      </div>
                    </div>
                  </div>

                  <div class="form-group row">
                    <div class= "col-sm-4 col-form-label">
                      <%= "<strong>Fecha de mantenimiento</strong>".html_safe%>
                    </div>
                    <div class=" col-sm-7">
                      <div class="form-control">
                        <%= @maintaince.date %>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="offset-sm-2 col-sm-2">
                      <%= link_to "Atrás", :back , class:"btn btn-primary fa fa-arrow-left"%>
                    </div>
                    <div class=" col-sm-1">
                      <%= link_to 'Editar', edit_device_maintaince_path(@maintaince.device), class:"btn btn-primary fa fa-edit" %>
                    </div>
                    <div class=" offset-sm-2 col-sm-2">
                      <%=link_to 'mantenimientos', device_maintainces_path(@device),class:"btn btn-primary fa fa-cog"%>
                    </div>
                  </div>
                </form>
              </div><!-- /.card-body -->
            </div>
            <!-- /.nav-tabs-custom -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <%=render 'layouts/partials/footer'%>
  </div>
</div>