config/routes.rb
Rails.application.routes.draw do
  post 'messages', to: "messages#create"
  mount Ckeditor::Engine => '/ckeditor'
  resources :notifications
  resources :vacations
  resources :salaries do
    get '/try_salary', to: 'salaries#try_salary', as: 'try_salary', on: :collection
  end
  resources :contracts
  get 'welcome/index'
  get 'welcome/indexlog'
  resources :application do
    get 'application/current_language', to: 'application#current_language', as: 'c_language', on: :collection
  end
  resources :languages do
      get '/change_language', to: 'languages#change_language', as: 'change_language', on: :collection

      get '/current_language', to: 'languages#current_language', as: 'c_language', on: :collection
  end


  resources :events
  resources :devices do
    get '/devices.xls', to: 'devices#report_devices', as: 'export', on: :collection
    collection {post :import}
    resources :maintainces do
      get '/device_maintainces.xls', to: 'maintainces#export_maintainces', as: 'export', on: :collection
    end
  end

  resources :users,:only => [:edit,:update]
  get 'users/index', to: 'users#index'
  get 'users/disabled_users_index', to: 'users#disabled_users_index', as: 'disabled_users_index'
  get 'users/:id/edit', to: 'users#edit'
  put 'users/:id/update', to: 'users#update'
  get 'users/:id/reset_password', to: 'users#reset_password', as: 'users_reset_password'
  get 'users/:id/disable_user', to: 'users#disable_user', as: 'user_disable'
  get 'users/:id/enable_user', to: 'users#enable_user', as: 'user_enable'


	devise_for :users, controllers: {
  	registrations: 'users/registrations',
  	sessions: 'users/sessions',
  	passwords: 'users/passwords',
  }

  authenticated :user do
  	root "welcome#indexlog", as: "authenticated_root"
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/device.rb
class Device < ApplicationRecord
	belongs_to :user
	has_many :maintainces, :dependent => :delete_all

	def self.to_csv(options = {})
		CSV.generate(options) do |csv|
		end

	end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  # GET /devices
  # GET /devices.json
  def index

  respond_to do |format|
    format.html
    format.json { render json: DeviceDatatable.new(params,{edit: edit_device_path('_'),show: device_path('_'),current_user: current_user}) }
  end
end
  # GET /devices/1
  # GET /devices/1.json
  def show
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  # POST /devices.json
  def create
    @device = current_user.devices.new(device_params)
    respond_to do |format|
      if @device.save
        format.html { redirect_to @device, success: t('app_common.models.devices.actions.created') }
        format.json { render :show, status: :created, location: @device }
      else
        format.html { render :new }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /devices/1
  # PATCH/PUT /devices/1.json
  def update
    respond_to do |format|
      if @device.update(device_params)
        format.html { redirect_to @device, info: t('app_common.models.devices.actions.updated') }
        format.json { render :show, status: :ok, location: @device }
      else
        format.html { render :edit }
        format.json { render json: @device.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /devices/1
  # DELETE /devices/1.json
  def destroy
    @device.destroy
    respond_to do |format|
      format.html { redirect_to devices_url, danger: 'Device was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def report_devices
    @devices = User.joins(:devices).select('users.full_name, devices.name,
    devices.type_of_device, devices.number, devices.operative_system,
    devices.processor, devices.memory, devices.mac')
    #La variable @personal contiene a la lista del personal de una empresa x.
    render xlsx: 'Reporte de dispositivos existentes '+ Time.now.to_s,
        template: 'reports/export_devices.xlsx.axlsx'

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_device
      @device = Device.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def device_params
      params.require(:device).permit(:name, :type_of_device, :number, :operative_system, :processor, :memory, :mac)
    end
end

app/helpers/devices_helper.rb
module DevicesHelper

	def options_for_type_of_device
    	['Teclado','Mouse',
    	'Pantalla','Computador']
 
	end

	def options_for_operative_system
		['Linux 32 bits', 'Linux 64 bits','MacOs 64bits', 
		'Windows 8 32 bits', 'Windows 8 64 bits',
		'Windows 10 32 bits', 'Windows 10 64 bits','Otro',
		'No tiene'
		 ]
	end

	def options_for_processor
		['Intel core i3 de tercera gen.','Intel core i3 de cuarta gen.',
		'Intel core i3 de quinta gen.', 'Intel core i3 de sexta gen.',
		'Intel core i3 de octava gen.', 'Intel core i3 de novena gen.',
		'Intel core i5 de tercera gen.','Intel core i5 de cuarta gen.',
		'Intel core i5 de quinta gen.', 'Intel core i5 de sexta gen.',
		'Intel core i5 de octava gen.', 'Intel core i5 de novena gen.',
		'Intel core i7 de tercera gen.','Intel core i7 de cuarta gen.',
		'Intel core i7 de quinta gen.', 'Intel core i7 de sexta gen.',
		'Intel core i7 de octava gen.', 'Intel core i7 de novena gen.',
		'Intel core i9 de tercera gen.','Intel core i9 de cuarta gen.',
		'Intel core i9 de quinta gen.', 'Intel core i9 de sexta gen.',
		'Intel core i9 de octava gen.', 'Intel core i9 de novena gen.',
		'Otro tipo de procesador intel','Procesador AMD','No tiene']
		
	end

	def options_for_memory
		['512MB DDR3', '1 GB DDR3',
		'2GB DDR3', '4GB DDR3', '8GB DDR3',
		'16GB DDR3', '32GB DDR3', '64GB DDR3',
		'512MB DDR4', '1 GB DDR4' ,'2GB DDR4', 
		'4GB DDR4', '8GB DDR4','16GB DDR4',
		 '32GB DDR4', '64GB DDR4', 'No tiene']
		
	end
		


end

app/views/devices/_form.html.erb

<div class="card-body">
  <%= form_with(model: device, local: true) do |f| %>
    <% if device.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% device.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <form class="form-horizontal">
    <div class="form-group row">
      <%= f.label :name,t('activerecord.attributes.device.name'), class:"col-sm-3 col-form-label" %>
      <div class="col-sm-8">
        <%= f.text_field :name, autofocus: true, autocomplete: "text" , class:"form-control"%>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :type_of_device, t('activerecord.attributes.device.type_of_device'), class: "col-sm-3 col-form-label" %>
      <div class="col-sm-8">
        <%= f.select :type_of_device, options_for_type_of_device,{:include_blank => t('app_common.selector.select_type') }, class:"form-control"%> 
      </div>
    </div>
    <div class="form-group row">
      <%=f.label :number, t('activerecord.attributes.device.number'), class:"col-sm-3 col-form-label"%>
      <div class="col-sm-8">
        <%= f.text_field :number, required: true, autofocus: true, class:"form-control"%>
      </div>
    </div>
    <div class="form-group row">
      <%=f.label :operative_system, t('activerecord.attributes.device.operative_system'), class:"col-sm-3 col-form-label"%>
      <div class="col-sm-8">
        <%=f.select :operative_system, options_for_operative_system,{:include_blank=> t('app_common.selector.select_os')}, class:"form-control"%>
      </div>
    </div>
     <div class="form-group row">
      <%=f.label :processor, t('activerecord.attributes.device.proccesor'), class:"col-sm-3 col-form-label"%>
      <div class="col-sm-8">
        <%=f.select :processor, options_for_processor,{:include_blank=> t('app_common.selector.select_processor')}, class:"form-control"%>
      </div>
    </div>
     <div class="form-group row">
      <%=f.label :memory, t('activerecord.attributes.device.memory'), class:"col-sm-3 col-form-label"%>
      <div class="col-sm-8">
        <%=f.select :memory, options_for_memory,{:include_blank=> t('app_common.selector.select_ram')}, class:"form-control"%>
      </div>
    </div>
     <div class="form-group row">
      <%=f.label :mac, t('activerecord.attributes.device.mac'), class:"col-sm-3 col-form-label"%>
      <div class="col-sm-8">
        <%= f.text_field :mac, autofocus: true, class:"form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="offset-sm-2 col-sm-8">
        <%= f.submit class:"btn btn-primary" %>
      </div>
    </div>
    <div class="form-group row">
      <div class="offset-sm-2 col-sm-8">
        <%= link_to t('helpers.button.back'), :back , class:"btn btn-primary fa fa-arrow-left"%>
      </div>
    </div>
  </form>
  <% end %>
</div><!-- /.card-body -->

app/views/devices/edit.html.erb
<%=render 'layouts/partials/navbar'%>
<div class="center-style-app">
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <h2><%=t('activerecord.models.device.other')%></h2>
            <div class="card card-primary">
              <div class="card-header">
                <h3><%=t('app_common.edits.editing', model: model_name_singular(Device))%> <%=@device.name%></h3>
                <div class="card-tools">
                  <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                          title="Collapse">
                    <i class="fa fa-minus"></i></button>
                </div>
              </div>
              <div class="card-body">
                <%= form_for(@device, url: {action: 'update'}, html: { method: :put, class: 'form-horizontal' }) do |f| %>
                  <% if @device.errors.any? %>
                    <div id="error_explanation">
                      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this @device from being saved:</h2>

                      <ul>
                      <% @device.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                      <% end %>
                      </ul>
                    </div>
                  <% end %>
                <form class="form-horizontal">
                  <div class="form-group row">
                    <%= f.label :name,t('activerecord.attributes.device.name'), class:"col-sm-3 col-form-label" %>
                    <div class="col-sm-8">
                      <%= f.text_field :name, autofocus: true, autocomplete: "text" , class:"form-control"%>
                    </div>
                  </div>
                  <div class="form-group row">
                    <%= f.label :type_of_device, t('activerecord.attributes.device.type_of_device'), class: "col-sm-3 col-form-label" %>
                    <div class="col-sm-8">
                      <%= f.select :type_of_device, options_for_type_of_device,{},selected: @device.type_of_device, class:"form-control"%> 
                    </div>
                  </div>
                  <div class="form-group row">
                    <%=f.label :number, t('activerecord.attributes.device.number'), class:"col-sm-3 col-form-label"%>
                    <div class="col-sm-8">
                      <%= f.text_field :number, required: true, autofocus: true, class:"form-control"%>
                    </div>
                  </div>
                  <div class="form-group row">
                    <%=f.label :operative_system,t('activerecord.attributes.device.operative_system'), class:"col-sm-3 col-form-label"%>
                    <div class="col-sm-8">
                      <%=f.select :operative_system, options_for_operative_system,{},selected: @device.operative_system, class:"form-control"%>
                    </div>
                  </div>
                   <div class="form-group row">
                    <%=f.label :processor, t('activerecord.attributes.device.proccesor'), class:"col-sm-3 col-form-label"%>
                    <div class="col-sm-8">
                      <%=f.select :processor, options_for_processor,{}, selected: @device.processor, class:"form-control"%>
                    </div>
                  </div>
                   <div class="form-group row">
                    <%=f.label :memory,t('activerecord.attributes.device.memory'), class:"col-sm-3 col-form-label"%>
                    <div class="col-sm-8">
                      <%=f.select :memory, options_for_memory,{}, selected: @device.memory, class:"form-control"%>
                    </div>
                  </div>
                   <div class="form-group row">
                    <%=f.label :mac, t('activerecord.attributes.device.mac'), class:"col-sm-3 col-form-label"%>
                    <div class="col-sm-8">
                      <%= f.text_field :mac, autofocus: true, class:"form-control" %>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="offset-sm-2 col-sm-8">
                      <%= f.submit t('helpers.submit.update', model: model_name_singular(Device)), class:"btn btn-primary" %>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="offset-sm-2 col-sm-8">
                      <%= link_to t('helpers.button.back'), :back , class:"btn btn-primary fa fa-arrow-left"%>
                    </div>
                  </div>
                </form>
                <% end %>
              </div><!-- /.card-body -->
            </div>
            <!-- /.nav-tabs-custom -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <%=render 'layouts/partials/footer'%>
  </div>
</div>
    

app/views/devices/index.html.erb
<%= render 'layouts/partials/navbar'%>
<div class="content-wrapper">
  <!-- Content Header (Page header) -->
  <section class="content-header">
    <div class="container-fluid">
      <div class="col-md-12">
        <p id="notice"><%= notice %></p>
        <h1><%=t('activerecord.models.device.other')%></h1>
        <div style="margin-bottom: 20px;margin-top: 20px; ">
          <%if can? :create, Device%>
            <%= link_to t('helpers.button.add', model: model_name_singular(Device)), new_device_path, class:'btn btn-primary '%>
          <%end%>
          <%= link_to 'Exportar Excel',export_devices_path(), class:'btn btn-primary '%>
        </div>
        <table id="devices-datatable" data-source="<%= devices_path(format: :json) %>">
          <thead>
            <tr>
              <th><%=Device.human_attribute_name(:owner)%></th>
              <th><%=Device.human_attribute_name(:name)%></th>
              <th><%=Device.human_attribute_name(:type_of_device)%> </th>
              <th><%=Device.human_attribute_name(:number)%> </th>
              <th><%=Device.human_attribute_name(:operative_system)%></th>
              <th><%=Device.human_attribute_name(:processor)%> </th>
              <th><%=Device.human_attribute_name(:memory)%></th>
              <th><%=Device.human_attribute_name(:mac)%></th>
              <th><%=t('app_common.tables.options')%></th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
  </section>
  <%=render 'layouts/partials/footer'%>
</div>
<script>
  document.addEventListener('turbolinks:load', function() {
    devicesdt.ajax_datatable('#devices-datatable');
  });
</script>

app/views/devices/new.html.erb
<%=render 'layouts/partials/navbar'%>

<div class="center-style-app">
  <div class="content-wrapper">
  <!-- Main content -->
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <h2><%=t('activerecord.models.device.other')%></h2>
          <div class="card card-primary">
            <div class="card-header">
              <h3><%=t('helpers.submit.create', model: model_name_singular(Device))%></h3>
              <div class="card-tools">
                <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                        title="Collapse">
                  <i class="fa fa-minus"></i></button>
              </div>
            </div>
            <%= render 'form', device: @device %>
          </div>
          <!-- /.nav-tabs-custom -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>
  <!-- /.content -->
  <%=render 'layouts/partials/footer'%>
  </div>
</div>

app/views/devices/show.html.erb
<%=render 'layouts/partials/navbar'%>
<div class="center-style-app">
  <div class="content-wrapper">
    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <h2><%=t('activerecord.models.device.other')%></h2>
            <p id="notice"><%= notice %></p>
            <div class="card card-primary">
              <div class="card-header">
                <h3><%=t('app_common.shows.showing', model: model_name_singular(Device))%> <%=@device.name%></h3>
                <div class="card-tools">
                    <i class="fa fa-sync-alt"></i>
                  <button type="button" class="btn btn-tool btn-sm" data-card-widget="collapse" data-toggle="tooltip"
                          title="Collapse">
                    <i class="fa fa-minus"></i></button>
                </div>
              </div>
              <div class="card-body">
                <form class="form-horizontal">
                  <div class="form-group row">
                    <div class= "col-sm-4 col-form-label">
                      <strong><%= t('activerecord.attributes.device.owner')%></strong>
                    </div>
                    <div class=" col-sm-7">
                      <div class="form-control">
                        <%= @device.user.full_name%>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class= "col-sm-4 col-form-label">
                      <strong><%= t('activerecord.attributes.device.name')%></strong>
                    </div>
                    <div class=" col-sm-7">
                      <div class="form-control">
                        <%= @device.name%>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class= "col-sm-4 col-form-label">
                      <strong><%= t('activerecord.attributes.device.type_of_device')%></strong>
                    </div>
                    <div class=" col-sm-7">
                      <div class="form-control">
                        <%= @device.type_of_device%>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class= "col-sm-4 col-form-label">
                      <strong><%= t('activerecord.attributes.device.number')%></strong>
                    </div>
                    <div class=" col-sm-7">
                      <div class="form-control">
                        <%= @device.number%>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class= "col-sm-4 col-form-label">
                      <strong><%= t('activerecord.attributes.device.operative_system')%></strong>
                    </div>
                    <div class=" col-sm-7">
                      <div class="form-control">
                        <%= @device.operative_system%>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class= "col-sm-4 col-form-label">
                      <strong><%= t('activerecord.attributes.device.processor')%></strong>
                    </div>
                    <div class=" col-sm-7">
                      <div class="form-control">
                        <%= @device.processor%>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class= "col-sm-4 col-form-label">
                      <strong><%= t('activerecord.attributes.device.memory')%></strong>
                    </div>
                    <div class=" col-sm-7">
                      <div class="form-control">
                        <%= @device.memory%>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class= "col-sm-4 col-form-label">
                     <strong><%= t('activerecord.attributes.device.mac')%></strong>
                    </div>
                    <div class=" col-sm-7">
                      <div class="form-control">
                        <%= @device.mac%>
                      </div>
                    </div>
                  </div>
                  <div class="form-group row">
                    <div class="offset-sm-2 col-sm-2">
                      <%= link_to t('helpers.button.back'), :back , class:"btn btn-primary fa fa-arrow-left"%>
                    </div>
                    <div class=" col-sm-1">
                      <%= link_to t('helpers.button.edit'), edit_device_path(@device), class:"btn btn-primary fa fa-edit" %>
                    </div>
                    <div class="offset-sm-2 col-sm-2">
                      <%=link_to t('activerecord.models.maintaince.other'), device_maintainces_path(@device),class:"btn btn-primary fa fa-cog"%>
                    </div>
                  </div>
                </form>
              </div><!-- /.card-body -->
            </div>
            <!-- /.nav-tabs-custom -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
    <%=render 'layouts/partials/footer'%>
  </div>
</div>