config/routes.rb
Rails.application.routes.draw do
  post 'messages', to: "messages#create"
  mount Ckeditor::Engine => '/ckeditor'
  resources :notifications
  resources :vacations
  resources :salaries do
    get '/try_salary', to: 'salaries#try_salary', as: 'try_salary', on: :collection
  end
  resources :contracts
  get 'welcome/index'
  get 'welcome/indexlog'
  resources :application do
    get 'application/current_language', to: 'application#current_language', as: 'c_language', on: :collection
  end
  resources :languages do
      get '/change_language', to: 'languages#change_language', as: 'change_language', on: :collection

      get '/current_language', to: 'languages#current_language', as: 'c_language', on: :collection
  end


  resources :events
  resources :devices do
    get '/devices.xls', to: 'devices#report_devices', as: 'export', on: :collection
    collection {post :import}
    resources :maintainces do
      get '/device_maintainces.xls', to: 'maintainces#export_maintainces', as: 'export', on: :collection
    end
  end

  resources :users,:only => [:edit,:update]
  get 'users/index', to: 'users#index'
  get 'users/disabled_users_index', to: 'users#disabled_users_index', as: 'disabled_users_index'
  get 'users/:id/edit', to: 'users#edit'
  put 'users/:id/update', to: 'users#update'
  get 'users/:id/reset_password', to: 'users#reset_password', as: 'users_reset_password'
  get 'users/:id/disable_user', to: 'users#disable_user', as: 'user_disable'
  get 'users/:id/enable_user', to: 'users#enable_user', as: 'user_enable'


	devise_for :users, controllers: {
  	registrations: 'users/registrations',
  	sessions: 'users/sessions',
  	passwords: 'users/passwords',
  }

  authenticated :user do
  	root "welcome#indexlog", as: "authenticated_root"
  end

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/partials/_flash_messages.html.erb
<% if flash.present? %>
  <div id='flash'>
   <script>
     <% if flash[:success] %>
       var $toastContent = $('<span><%= flash[:success] %></span>');
       toastr.options={"closeButton": true};
       toastr.success($toastContent)
     <% end %>
     <% if flash[:info] %>
       var $toastContent = $('<span><%= flash[:info] %></span>');
       toastr.options={"closeButton": true};
       toastr.info($toastContent)
     <% end %>
     <% if flash[:danger] %>
       var $toastContent = $('<span><%= flash[:danger] %></span>');
       toastr.options={"closeButton": true};
       toastr.error($toastContent)
     <% end %>
   </script>
  </div>
<% end %>

app/views/layouts/partials/_footer.html.erb
<footer class="main-footer">
	<div class="float-right d-none d-sm-block">
	  <b>Version</b> 0.5 
	</div>
	<strong>Copyright &copy; 2020-2022 <a href="https://www.aguasdelparamo.com">Aguas del páramo</a>.</strong> Derechos reservados
</footer>

app/views/layouts/partials/_language_switcher.html.erb
<div class="dropdown pull-left" id="links-languages">
  <button aria-expanded="true" aria-haspopup="true" class="btn btn-default" data-toggle="dropdown" id="dropdownLanguage" type="button" data-abbr="<%= I18n.locale.to_s %>"><%= t('helpers.button.switch', model: model_name_singular(Language))%>
    <span class="flag-icon flag-icon-<%= I18n.locale.to_s %>"></span>
    <span class="caret"></span>
  </button>
  <ul aria-labelledby="dropdownLanguage" class="dropdown-menu btn btn-default">
    <% Language.where.not(abbreviation: I18n.locale.to_s).each do |language| %>
      <li>
        <a class="change_language" data-abbr="<%= language.abbreviation %>" data-url="<%= change_language_languages_path %>">
          <span class="flag-icon flag-icon-<%= language.abbreviation %>"></span>
          <span>
            <%= language.description %>
          </span>
        </a>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/partials/_navbar.html.erb
<div class="hold-transition sidebar-mini layout-fixed">
  <!-- Site wrapper -->
  <div class="wrapper">
    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" data-widget="pushmenu"  role="button"><i class="fa fa-bars"></i></a>
        </li>
         <li class="nav-item dropdown">
          <a class="nav-link" data-toggle="dropdown" href="#">
            <i class="fa fa-comments"></i>
            <span class="badge badge-danger navbar-badge">3</span>
          </a>
        <!-- Notifications Dropdown Menu -->
          <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
              <i class="fa fa-bell"></i>
                <span class="badge badge-warning navbar-badge"><%=Notification.owned(current_user.id).created.count%></span>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-left">
              <%Notification.owned(current_user.id).created.order(created_at: :desc).each do |notify|%>
                <a href="" class="dropdown-item">
                  <i class="fa fa-users mr-2"></i> <%= notify.message %>
                  <span class="float-right text-muted text-sm"><%= time_ago_in_words(notify.created_at)%></span>
                </a>
              <%end%>
              <!-- <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item">
                <i class="fa fa-users mr-2"></i> 8 friend requests
                <span class="float-right text-muted text-sm">12 hours</span>
              </a>
              <div class="dropdown-divider"></div>
              <a href="#" class="dropdown-item">
                <i class="fa fa-file mr-2"></i> 3 new reports
                <span class="float-right text-muted text-sm">2 days</span>
              </a> -->
          </li>
        <%=render 'layouts/partials/language_switcher'%>
      </ul>

      <!-- SEARCH FORM -->



    </nav>
    <!-- /.navbar -->

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
      <!-- Brand Logo -->
      <div  class="brand-link">
        <%= image_tag 'logo.jpg', alt:"APS",
             class:"brand-image img-circle elevation-3",
             style:"opacity: .8",size:"64"  %>
        <span class="brand-text font-weight-light">APS</span>
      </div>

      <!-- Sidebar -->
      <div class="sidebar">

        <!-- Sidebar user (optional) -->
        <nav class="mt-2">

          <ul id = "bar_name" class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
            <li  class="nav-item has-treeview">
              <div class="nav-link user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="info">
                  <a  class="d-block">
                    <%=current_user.full_name%>
                    <i id="caretid" class="right fa fa-caret-left"></i>
                  </a>
                </div>
              </div>
            </li>
            <ul id= "show_bar" class="nav nav-treeview">
              <%=render 'layouts/partials/profile'%>
              <li class="nav-item">
                <div class="nav-link">
                  <i class="fa fa-sign-out"></i>
                  <p><%= link_to t('app_common.navbar.close_session'), destroy_user_session_path , method: :delete ,style:"font-size: 1.5rem;"%></p>
                </div>
              </li>
            </ul>
          </ul>
        </nav>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
          <ul class="nav nav-pills nav-sidebar flex-column">
            <%if can? :read, User %>
              <li class="nav-item">
                <div  class="nav-link user-panel mt-3 pb-3 mb-3 d-flex">
                  <p>
                      <i class=" fa fa-user"></i>
                      <%=link_to t('app_common.navbar.users'), users_index_path, style:"font-size: 1.5rem;color:white;"%></p>
                    <span class="right badge badge-danger"></span>
                  </div>
              </li>
            <%end%>
            <%if can? :read, Salary %>
              <li class="nav-item">
                <div  class="nav-link user-panel mt-3 pb-3 mb-3 d-flex">
                  <p>
                      <i class=" fa fa-money  "></i>
                      <%=link_to t('app_common.navbar.salaries'), salaries_path, style:"font-size: 1.5rem;color:white;"%></p>
                    <span class="right badge badge-danger"></span>
                  </div>
              </li>
            <%end%>
            <%if can? :read, Vacation %>
              <li class="nav-item">
                <div  class="nav-link user-panel mt-3 pb-3 mb-3 d-flex">
                  <p>
                      <i class=" fa fa-plane"></i>
                      <%=link_to t('app_common.navbar.vacations'), vacations_path, style:"font-size: 1.5rem;color:white;"%></p>
                    <span class="right badge badge-danger"></span>
                  </div>
              </li>
            <%end%>
            <%if can? :read, Contract %>
              <li class="nav-item">
                <div  class="nav-link user-panel mt-3 pb-3 mb-3 d-flex">
                  <p>
                      <i class=" fa fa-folder"></i>
                      <%=link_to t('app_common.navbar.contracts'), contracts_path, style:"font-size: 1.5rem;color:white;"%></p>
                    <span class="right badge badge-danger"></span>
                  </div>
              </li>
            <%end%>
            <%if can? :read, Device %>
              <li class="nav-item">
                <div  class="nav-link user-panel mt-3 pb-3 mb-3 d-flex">
                  <p>
                      <i class=" fa fa-tv"></i>
                      <%=link_to t('app_common.navbar.devices'), devices_path, style:"font-size: 1.5rem;color:white;"%></p>
                    <span class="right badge badge-danger"></span>
                  </div>
              </li>
            <%end%>
            <%if can? :read,Event %>
              <li class="nav-item">
                <div  class="nav-link user-panel mt-3 pb-3 mb-3 d-flex">
                  <p>
                      <i class="fa fa-calendar "></i>
                      <%=link_to t('app_common.navbar.meetings'), events_path, style:"font-size: 1.5rem;color:white;"%></p>
                    <span class="right badge badge-danger"></span>
                  </div>
              </li>
            <%end%>
          </ul>
        </nav>
        <!-- /.sidebar-menu -->
      </div>
      <!-- /.sidebar -->
    </aside>
      <!-- /.content -->
  </div>
    <!-- /.content-wrapper -->
</div>
<script type="text/javascript">

    document.addEventListener('turbolinks:load', function() {
      $('#bar_name').click(function(event) {
        $('#caretid').removeClass('fa-caret-left').addClass('fa-caret-down');
        $('#show_bar').slideDown( "slow", function() {
          });
        });
      });
</script>

app/views/layouts/partials/_profile.erb
<%if current_user.is_gerente? || current_user.is_subgerente? ||
current_user.is_cooradmin_fin? || current_user.is_coorcomer_soc? ||
current_user.is_coortec_ambac? || current_user.is_coortec_ambas?%>
  <li class="nav-item">
    <div  class="nav-link">
      <i class="fa fa-circle nav-icon"></i>
      <p><%=link_to t('app_common.navbar.profile.edit_profile'), edit_user_registration_path, style:"font-size: 1.5rem;"%></p>
    </div>
  </li>
<%end%>